from app.core.config import settings
from app.core.security import get_password_hash
from app.models.admin_user import AdminUser
from app.models.category import Category
from app.models.point import Point


DEFAULT_CATEGORIES = [
    {
        "name": "城市公园",
        "slug": "parks",
        "icon": "park",
        "sort_order": 1,
        "description": "面向居民日常休闲、散步和亲子活动的免费公共绿地。",
    },
    {
        "name": "社区服务中心",
        "slug": "community-centers",
        "icon": "community",
        "sort_order": 2,
        "description": "提供社区事务、活动组织和基础民生服务的综合场所。",
    },
    {
        "name": "政务服务大厅",
        "slug": "government-service",
        "icon": "service",
        "sort_order": 3,
        "description": "集中办理政务事项、便民审批和窗口服务。",
    },
    {
        "name": "公共卫生间",
        "slug": "public-restrooms",
        "icon": "restroom",
        "sort_order": 4,
        "description": "提供免费对外开放的基础卫生设施。",
    },
]


DEFAULT_POINTS = [
    {
        "category_slug": "parks",
        "name": "滨江市民公园",
        "address": "海棠路 108 号滨江绿地入口",
        "opening_hours": "全天开放",
        "description": "园内包含步行道、儿童活动区和无障碍休息设施，适合家庭与老年居民休闲。",
        "service_content": "休闲散步、晨练、公益活动场地",
        "target_people": "周边居民、亲子家庭、老年人",
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "和安社区综合服务中心",
        "address": "和平街道和安路 66 号",
        "opening_hours": "周一至周五 08:30-17:30",
        "description": "提供老年助餐咨询、社区文化活动报名和基层便民窗口服务。",
        "service_content": "社区咨询、活动报名、便民代办",
        "target_people": "社区居民、老年人、志愿者",
        "image_url": "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "营门口社区卫生服务中心",
        "district": "金牛区",
        "street": "营门口街道",
        "address": "一品天下大街836号",
        "landmark": "一品天下美食街、金牛区图书馆",
        "navigation_notes": "导航“营门口社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "金牛区公益非营利性社区卫生服务机构，执行基本药物零差率销售，服务周边居民日常就医与健康管理需求。",
        "service_content": "全科诊疗、中医康复、妇幼保健、计划免疫、慢性病管理、健康教育",
        "target_people": "营门口街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "金泉社区卫生服务中心",
        "district": "金牛区",
        "street": "金泉街道",
        "address": "信息园西路120号",
        "landmark": "中海国际社区、成都外国语学校",
        "navigation_notes": "导航“金泉社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "面向金泉街道辖区居民提供基础诊疗与公共卫生服务，兼顾家庭医生与健康管理需求。",
        "service_content": "基本医疗、公共卫生、健康管理、家庭医生签约",
        "target_people": "金泉街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "西华社区卫生服务中心",
        "district": "金牛区",
        "street": "西华街道",
        "address": "侯家桥一街288号",
        "landmark": "西华街道办事处、侯家桥社区",
        "navigation_notes": "导航“西华社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:30-17:00（建议电话确认）",
        "description": "业务用房面积约5044平方米，覆盖7个社区、服务常住人口约10.9万人，提供社区常见诊疗和康复保健服务。",
        "service_content": "全科诊断、妇科、产后康复、中医理疗、计划免疫、儿童保健、妇女保健、康复理疗、健康教育",
        "target_people": "西华街道及周边社区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "人民北路社区卫生服务中心（金牛区第二人民医院）",
        "district": "金牛区",
        "street": "人民北路街道",
        "address": "花牌坊街1号附6号",
        "landmark": "花牌坊、金牛区人民政府",
        "navigation_notes": "导航“人民北路社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:30-17:30",
        "description": "又称金牛区第二人民医院，设有嗓音专科门诊；并于2025年12月在抚琴街道金沙路191号增设抚琴分中心。",
        "service_content": "基本医疗、嗓音专科、公共卫生服务",
        "target_people": "人民北路街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "驷马桥曹家巷社区卫生服务中心（金牛区第四人民医院）",
        "district": "金牛区",
        "street": "驷马桥街道",
        "address": "马鞍东路2号 / 解放路二段173号（两个院区）",
        "landmark": "曹家巷、红星路",
        "navigation_notes": "地铁3号线至“红星桥站”或“驷马桥站”；附近公交站“簸箕街站”步行约3分钟。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "又称金牛区第四人民医院，设有两个院区，承担社区基础医疗与公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "驷马桥街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "沙河源社区卫生服务中心（金建人民医院）",
        "district": "金牛区",
        "street": "沙河源街道",
        "address": "古柏路32号 / 川建南一路129号 / 韦家碾三路169-179号（三个院区）",
        "landmark": "沙河源公园、金建小学",
        "navigation_notes": "导航“沙河源社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "又称金建人民医院，设有三个院区，可提供街道范围内基础医疗与公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "沙河源街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/0b55b804ab9dda6b028d4ba041dbdbfcd944f51b_size952_w1080_h604.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "荷花池社区卫生服务中心",
        "district": "金牛区",
        "street": "荷花池街道",
        "address": "站北北街149号 / 西北桥北街316号（荷花池院区）",
        "landmark": "荷花池批发市场、成都火车北站",
        "navigation_notes": "地铁5号线至“北站西二路站”D口出，步行约500米；或乘17路、33路、73路、95路、K1线至二环商贸大道口站。",
        "opening_hours": "周一至周五 08:00-17:00（法定节假日除外）",
        "description": "2024年12月新启用荷花池院区，服务面积约2.23平方公里，覆盖人口4万余人。",
        "service_content": "全科、中医科、口腔科、眼科、儿童保健、预防接种、心脏康复、心理健康指导",
        "target_people": "荷花池街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "天回社区卫生服务中心",
        "district": "金牛区",
        "street": "天回镇街道",
        "address": "天回镇天歌路940号",
        "landmark": "天回镇、成都植物园",
        "navigation_notes": "导航“天回社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "服务天回镇街道辖区居民，提供社区常见基础医疗与公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "天回镇街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "西安路社区卫生服务中心",
        "district": "金牛区",
        "street": "西安路街道",
        "address": "文华路3号",
        "landmark": "成都中医药大学附属医院约729米、四川省人民医院约1.1公里",
        "navigation_notes": "导航“西安路社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "紧邻多家三甲医院，适合周边居民就近进行基础诊疗与公共卫生服务办理。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "西安路街道及周边居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "九里堤社区卫生服务中心",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "星河路90号附6号",
        "landmark": "九里堤、西南交通大学",
        "navigation_notes": "导航“九里堤社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "服务九里堤街道辖区居民，满足周边基础医疗和公共卫生服务需求。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "九里堤街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "黄忠社区卫生服务中心",
        "district": "金牛区",
        "street": "黄忠街道",
        "address": "黄苑街131号附103号",
        "landmark": "黄忠公园、金沙遗址博物馆（邻近）",
        "navigation_notes": "导航“黄忠社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "服务黄忠街道辖区居民，可就近获得基础医疗与公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "黄忠街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "茶店子社区卫生服务中心",
        "district": "金牛区",
        "street": "茶店子街道",
        "address": "育德路89号",
        "landmark": "新金牛公园、龙湖西宸天街",
        "navigation_notes": "导航“茶店子社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "服务茶店子街道辖区居民，适合在社区内办理常见基础医疗和公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "茶店子街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "抚琴社区卫生服务中心",
        "district": "金牛区",
        "street": "抚琴街道",
        "address": "金荣巷8号",
        "landmark": "抚琴小区",
        "navigation_notes": "导航“抚琴社区卫生服务中心”。",
        "opening_hours": "周一至周五 08:00-17:00（建议电话确认）",
        "description": "服务抚琴街道辖区居民，提供社区基础医疗与公共卫生服务。",
        "service_content": "基本医疗、公共卫生服务",
        "target_people": "抚琴街道辖区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "西华街道综合便民服务中心",
        "district": "金牛区",
        "street": "西华街道",
        "address": "金声路293号（唐掌门火锅旁）",
        "landmark": "西华街道办事处、唐掌门火锅",
        "navigation_notes": "导航“金牛区西华街道办事处”，前往金声路293号。",
        "opening_hours": "周一至周五 09:00-12:00，13:00-17:00（法定节假日除外）；延时服务：周六 09:00-17:00",
        "description": "街道综合便民服务中心，建设面积约506平方米，设有7个便民服务窗口，进驻事项达156项，咨询电话 028-87596190。",
        "service_content": "综合服务、社保服务、房屋租赁备案、退役军人服务等",
        "target_people": "西华街道居民及办事群众",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/e4e339f1fd887350112a9e2afa1a324b1fc513ba_size981_w1080_h726.png",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "community-centers",
        "name": "沙河源街道友联社区养老服务中心",
        "district": "金牛区",
        "street": "沙河源街道友联社区",
        "address": "沙河源街道友联社区（具体门牌号建议电话确认）",
        "landmark": "沙河源公园",
        "navigation_notes": "导航“友联社区养老服务中心”。",
        "opening_hours": "周一至周日（24小时呼叫中心服务）",
        "description": "成都市首个养老综合体，使用面积约2338平方米，设有40余张养老床位，提供医养结合与居家上门服务。",
        "service_content": "日托、全托、助餐、医养结合、康养服务、便民服务、居家上门服务、智能床位监控",
        "target_people": "老年人及其家庭、社区居民",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20200102/14/wemedia/0b55b804ab9dda6b028d4ba041dbdbfcd944f51b_size952_w1080_h604.png",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "government-service",
        "name": "市民政务服务大厅",
        "address": "政务路 1 号市民中心一层",
        "opening_hours": "周一至周五 09:00-17:00",
        "description": "可集中办理社保、公积金、户籍等常见事项，现场设有导办服务。",
        "service_content": "政务咨询、材料受理、自助打印",
        "target_people": "全体市民",
        "image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "public-restrooms",
        "name": "人民广场东侧公共卫生间",
        "address": "人民广场东入口旁",
        "opening_hours": "06:00-22:00",
        "description": "临近地铁口与广场主通道，配有无障碍厕位和母婴护理台。",
        "service_content": "免费卫生设施、无障碍服务",
        "target_people": "市民、游客、老年人、儿童",
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "public-restrooms",
        "name": "九里堤北路1号附2号公共卫生间",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "九里堤北路1号附2号",
        "landmark": "临近九里堤主干道，周边临街商铺",
        "navigation_notes": "沿九里堤北路行进，1号门牌旁即是公厕。",
        "opening_hours": "06:00-22:00",
        "description": "临街露天公共公厕，周边居民区密集，适合附近居民和过路行人使用。",
        "service_content": "免费公共如厕、便民洗手",
        "target_people": "周边居民、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "交桂二巷公厕（金牛-129）",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "交桂二巷2号附1号",
        "landmark": "交桂巷居民小区旁，临近街边菜市场",
        "navigation_notes": "进入交桂二巷往里走约30米，2号院落旁。",
        "opening_hours": "06:00-22:00",
        "description": "老式街巷公厕，周边老旧小区住户较多，满足社区日常基础便民需求。",
        "service_content": "免费卫生设施、便民如厕",
        "target_people": "周边居民、买菜市民",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "星辰东一街锦西民园北侧公厕",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "星辰东一街锦西民园西北侧约50米",
        "landmark": "锦西民园小区大门旁",
        "navigation_notes": "锦西民园西北门出门右转50米。",
        "opening_hours": "06:00-22:00",
        "description": "小区配套公共厕所，日常人流量稳定，方便居民与周边行人临时使用。",
        "service_content": "免费公厕、便民供水",
        "target_people": "小区居民、周边行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "西南交大九里校区公共厕所",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "唐臣路西南交大九里校园内",
        "landmark": "西南交大九里校区校园内，近校门",
        "navigation_notes": "交大九里校区正门入校，唐臣路沿路标识指引。",
        "opening_hours": "06:00-22:00",
        "description": "校园配套公厕，对外开放便民使用，方便师生和附近市民短暂停留时使用。",
        "service_content": "免费卫生间、饮水便民",
        "target_people": "师生、周边市民、访客",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "凯德广场金牛（交大路店B1洗手间）",
        "district": "金牛区",
        "street": "九里堤街道",
        "address": "交大路183号凯德广场负一楼",
        "landmark": "凯德金牛商场内部",
        "navigation_notes": "凯德广场1号门进商场，直梯下B1层。",
        "opening_hours": "10:00-22:00（商场营业时间）",
        "description": "商场室内公厕，环境较整洁，楼内多层分布，适合购物和休闲人群使用。",
        "service_content": "免费卫生间、母婴室、洗手台",
        "target_people": "商场顾客、亲子家庭、游客",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "沙湾印象汇商场F4洗手间",
        "district": "金牛区",
        "street": "沙湾片区",
        "address": "二环路北一段10号沙湾印象汇4楼",
        "landmark": "沙湾印象汇购物中心内",
        "navigation_notes": "沙湾印象汇商场1号门进店，扶梯直达4层。",
        "opening_hours": "10:00-22:00",
        "description": "商场室内公厕，配套齐全，环境整洁，适合购物和用餐人群使用。",
        "service_content": "免费卫生间、洗手台、商场配套便民服务",
        "target_people": "商场顾客、游客、周边居民",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "新金牛公园D区公共卫生间",
        "district": "金牛区",
        "street": "茶店子片区",
        "address": "茶店子路119号新金牛公园D区内",
        "landmark": "新金牛公园园区、公园休闲步道旁",
        "navigation_notes": "新金牛公园D区大门入园，中心绿地旁。",
        "opening_hours": "06:00-22:00",
        "description": "公园配套公厕，游园游客使用量较大，适合散步和休闲人群途中使用。",
        "service_content": "免费卫生设施、便民饮水",
        "target_people": "游客、周边居民、运动人群",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "金沙路16-1号公厕",
        "district": "金牛区",
        "street": "金沙片区",
        "address": "金沙路16-1号临街",
        "landmark": "金沙路沿街居民小区",
        "navigation_notes": "沿金沙路沿街寻找16号门牌即到。",
        "opening_hours": "06:00-22:00",
        "description": "街边老式社区公共厕所，方便沿街居民和过路行人日常使用。",
        "service_content": "免费便民如厕",
        "target_people": "周边居民、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "花牌坊街公厕",
        "district": "金牛区",
        "street": "花牌坊片区",
        "address": "花牌坊街123-10号",
        "landmark": "花牌坊沿街商铺、老式居民区",
        "navigation_notes": "花牌坊街中段，123号门牌旁巷道内。",
        "opening_hours": "06:00-22:00",
        "description": "老城区街巷配套公厕，服务沿街居民、商铺顾客和过路行人。",
        "service_content": "免费公共卫生服务",
        "target_people": "周边居民、商圈人群、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "加贝花园东南侧公共卫生间",
        "district": "金牛区",
        "street": "蜀明路片区",
        "address": "蜀明东路加贝花园东南侧约30米",
        "landmark": "加贝花园小区东南门",
        "navigation_notes": "加贝花园东南门出门右转30米。",
        "opening_hours": "06:00-22:00",
        "description": "小区外围配套便民公厕，适合周边居民日常短时使用。",
        "service_content": "免费如厕、洗手",
        "target_people": "周边居民、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "二环蜀汉路口东北侧公厕",
        "district": "金牛区",
        "street": "抚琴片区",
        "address": "二环路西三段与蜀汉路交叉口东北侧",
        "landmark": "二环高架下、路口公交站点旁",
        "navigation_notes": "蜀汉路与二环交叉口东北角路边。",
        "opening_hours": "06:00-22:00",
        "description": "路口临街公厕，途经行人较多，适合换乘和步行人群应急使用。",
        "service_content": "免费便民公厕",
        "target_people": "公交乘客、过路行人、周边居民",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "二环北四段89号公共卫生间",
        "district": "金牛区",
        "street": "驷马桥片区",
        "address": "二环路北四段89号1栋附38号",
        "landmark": "沿街居民楼，临街铺面",
        "navigation_notes": "二环路北四段89号居民院落旁。",
        "opening_hours": "全天24小时营业",
        "description": "全天候开放公厕，夜间也可使用，满足周边居民和过路人群的便民需求。",
        "service_content": "24小时免费卫生便民服务",
        "target_people": "周边居民、夜间出行人群、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "public-restrooms",
        "name": "抚琴西南路公厕",
        "district": "金牛区",
        "street": "抚琴片区",
        "address": "抚琴西南路4号附2号",
        "landmark": "抚琴老小区街巷内",
        "navigation_notes": "抚琴西南路4号院落侧边。",
        "opening_hours": "06:00-22:00",
        "description": "抚琴老旧社区配套公厕，方便周边居民在社区内就近使用。",
        "service_content": "免费便民如厕",
        "target_people": "周边居民、过路行人",
        "status": "draft",
    },
    {
        "category_slug": "government-service",
        "name": "金牛政务中心（成都市金牛区人民政府东）",
        "district": "金牛区",
        "street": "抚琴街道",
        "address": "金牛区抚琴街道沙湾路65号金牛政务中心7楼12号",
        "landmark": "临近沙湾路主干道，周边有临街商铺",
        "navigation_notes": "沿沙湾路行进至65号，进入金牛政务中心7楼12号。",
        "opening_hours": "周一至周六 09:00-17:00",
        "description": "金牛区政务服务办理点，提供政务事项办理、窗口咨询和便民服务，位于金牛政务中心内。",
        "service_content": "政务事项办理、窗口咨询、便民服务",
        "target_people": "金牛区居民及办事群众",
        "image_url": "http://store.is.autonavi.com/showpic/9d530b96f2c5b6fc49f1dbb3142dd0e6",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "government-service",
        "name": "金牛政务中心（成都市金牛区人民政府东）",
        "district": "金牛区",
        "street": "一品天下片区",
        "address": "金牛区一品天下大街999号（星河地铁站A口步行390米）",
        "landmark": "星河地铁站A口、一品天下大街",
        "navigation_notes": "乘地铁至星河站A口，出站后步行约390米。",
        "opening_hours": "周一至周六 09:00-17:00",
        "description": "金牛区政务服务办理点，靠近星河地铁站，适合到场办理常见政务事项和咨询服务。",
        "service_content": "政务事项办理、川渝通办、窗口咨询",
        "target_people": "金牛区居民及跨区域办事群众",
        "image_url": "http://store.is.autonavi.com/showpic/2d31d245a9d2d20ce3e4991d24e01c8e",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "government-service",
        "name": "成都市人民政府政务服务中心",
        "district": "青羊区",
        "address": "青羊区草市街2号成都市人民政府政务服务中心6层",
        "landmark": "临近草市街主干道，设有西门、北门、东门入口",
        "navigation_notes": "导航至青羊区草市街2号，进入政务中心6层；西门到达率较高，北门和东门也可进入。",
        "opening_hours": "周一至周五 09:00-12:00，13:00-17:00",
        "description": "市级政务服务中心，可办理市级政务事项，现场提供窗口咨询和便民服务。",
        "service_content": "市级政务事项办理、窗口咨询、便民服务",
        "target_people": "全体市民及企业办事人员",
        "image_url": "https://bkimg.cdn.bcebos.com/pic/34fae6cd7b899e510fb345cac0edce33c895d043a791",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "government-service",
        "name": "成华区人民政府政务服务中心",
        "district": "成华区",
        "street": "猛追湾街道",
        "address": "成华区猛追湾街道石油社区建设北路1段66号",
        "landmark": "建设北路1段，石油社区周边",
        "navigation_notes": "沿建设北路1段行至66号；西北门和地下停车场均可进入。",
        "opening_hours": "周一至周五 09:00-12:00，13:00-17:00",
        "description": "成华区区级政务服务中心，提供区级政务事项办理和窗口服务。",
        "service_content": "区级政务事项办理、窗口服务",
        "target_people": "成华区居民及办事群众",
        "image_url": "https://img0.baidu.com/it/u=1281639988,1212303067&fm=253&fmt=auto&app=138&f=JPEG?w=805&h=500",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "府河摄影公园",
        "district": "金牛区",
        "street": "沙河源街道新桥社区",
        "address": "北三环路一段南，东临锦江，西至北三环路一段",
        "landmark": "成都当代影像馆、沙河源派出所",
        "navigation_notes": "导航“府河摄影公园”，可乘公交至“新泉村站”。",
        "opening_hours": "全天（开放式公园）",
        "description": "以摄影为主题的开放式公园，内有公园式婚姻登记处，春季花卉丰富，适合休闲与拍照。",
        "service_content": "摄影创作、草坪休闲、花卉观赏",
        "target_people": "摄影爱好者、情侣、周边居民、游客",
        "image_url": "https://youimg1.c-ctrip.com/target/100c1e000001f6mt95A02.jpg",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "新金牛公园",
        "district": "金牛区",
        "street": "茶店子街道 / 营门口街道",
        "address": "茶店子正街，龙湖西宸天街旁",
        "landmark": "龙湖西宸天街、金牛体育中心",
        "navigation_notes": "地铁7号线茶店子站C口出即达。",
        "opening_hours": "全天（开放式公园）",
        "description": "成都较长的街心公园之一，是“高线公园”群核心，连接多个场馆和商圈空间。",
        "service_content": "儿童游乐、商圈购物、散步、草坪露营",
        "target_people": "亲子家庭、周边居民、运动休闲人群",
        "image_url": "https://p8.itc.cn/q_70/images03/20211207/9b9964d834034b9a99a699d77cb1c702.png",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "成都欢乐谷",
        "district": "金牛区",
        "street": "西华街道",
        "address": "西华大道16号",
        "landmark": "天府艺术公园、华侨城",
        "navigation_notes": "地铁6号线西华大道站D口；建议出行前查询当天营业安排。",
        "opening_hours": "通常 09:30-21:00（建议出行前查询）",
        "description": "大型主题乐园，拥有九个主题区，适合亲子和朋友结伴游玩，属于收费园区。",
        "service_content": "游乐设施、演艺表演、亲子娱乐",
        "target_people": "亲子家庭、年轻游客、主题乐园爱好者",
        "image_url": "https://ts1.tc.mm.bing.net/th/id/R-C.e2bddfca3c0ae57a5dfccbeab3daaaa2?rik=zz7s8p5UdH6yvA&riu=http%3a%2f%2fcd.happyvalley.cn%2fuploadfiles%2fpicture%2f2018-8-28%2f20188281128222755.jpg&ehk=TxeSz8SiWldmTRYV1uAy4ko1KcBIwYm6TsOg3zc7JkA%3d&risl=&pid=ImgRaw&r=0",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "成都植物园",
        "district": "金牛区",
        "street": "天回镇街道",
        "address": "蓉都大道天回路1116号",
        "landmark": "天回山、银杏园",
        "navigation_notes": "地铁3号线植物园站B口。",
        "opening_hours": "旺季(3-5月) 07:00-19:00；夏季(6-8月) 06:30-20:00",
        "description": "收费植物园，植物品种丰富，适合科普参观、赏花、拍照和家庭出游。",
        "service_content": "科普馆、观赏植物、婚纱摄影、大草坪野餐",
        "target_people": "亲子家庭、植物爱好者、游客",
        "image_url": "https://d.ifengimg.com/q100/img1.ugc.ifeng.com/newugc/20210430/5/wemedia/8f1356724c8c726ac52490096ee92b28981f27a9_size1556_w1600_h1067.jpg",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "沙河源公园",
        "district": "金牛区",
        "street": "沙河源街道",
        "address": "九里堤北路，府河摄影公园南侧",
        "landmark": "新桥国际社区",
        "navigation_notes": "位于“府河摄影公园”旁，可一并游览。",
        "opening_hours": "全天",
        "description": "以木文化为主题的城市公园，曾是成都重要的木材储运地，兼具休闲与文化展示功能。",
        "service_content": "文化展示、休闲散步、儿童设施",
        "target_people": "周边居民、亲子家庭、文化游览人群",
        "image_url": "https://ts1.tc.mm.bing.net/th/id/R-C.0c94afcb4f1da83e12b29ab9ee03bbbd?rik=GhSxSTzpIyTjHg&riu=http%3a%2f%2fwww.archina.com%2fdata%2fupload%2fueditor%2f20200411%2f5e90dc438cb20.jpg&ehk=j4bw86zhilQYy5zXU9wj0m88%3d&risl=&pid=ImgRaw&r=0",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "上新桥公园",
        "district": "金牛区",
        "street": "沙河源街道新桥社区",
        "address": "锦江公园金牛段西侧",
        "landmark": "下新桥公园（紧邻）、锦江塔",
        "navigation_notes": "与下新桥公园相连，建议定位“锦江塔”。",
        "opening_hours": "全天",
        "description": "拥有大草坪和地标性锦江塔，适合运动、观景和城市休闲打卡。",
        "service_content": "飞盘、篮球、跑步、观景打卡",
        "target_people": "运动人群、年轻游客、周边居民",
        "image_url": "https://sjcd-feiyuantu.oss-cn-hangzhou.aliyuncs.com/vdam-php/test/editorial/vdam/400/new/58c471ba6d7143be805d1ffce4869b07.jpg",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "成都露天音乐公园",
        "district": "金牛区",
        "street": "凤凰山街道",
        "address": "北三环路三段与北星大道交汇处",
        "landmark": "凤凰山体育中心",
        "navigation_notes": "地铁1号线韦家碾站下车后步行约10分钟。",
        "opening_hours": "06:00-22:00",
        "description": "以演出和城市活动为特色的公园空间，适合听演唱会、露营和户外运动。",
        "service_content": "听演唱会、露营、放风筝、极限运动",
        "target_people": "音乐爱好者、露营人群、年轻游客",
        "image_url": "https://k.sinaimg.cn/n/sinacn10114/480/w1800h1080/20190619/d4b8-hyrtarw1814449.jpg/w700d1q75cms.jpg",
        "is_featured": True,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "凤凰山公园",
        "district": "金牛区",
        "street": "凤凰山街道",
        "address": "三环路凤凰立交内侧",
        "landmark": "成都露天音乐公园、红星美凯龙",
        "navigation_notes": "建议自驾前往，停车位较充裕。",
        "opening_hours": "全天",
        "description": "地势较高、植被茂密的城市公园，适合登高、散步和自然观光。",
        "service_content": "登山健身、郊游、自然观光",
        "target_people": "登山健身人群、家庭游客、周边居民",
        "image_url": "https://youimg1.c-ctrip.com/target/100t13000000vesq14D61.jpg",
        "is_featured": False,
        "status": "published",
    },
    {
        "category_slug": "parks",
        "name": "蜀道通衢园",
        "district": "金牛区",
        "street": "天回镇街道",
        "address": "北星大道与聚霞路交汇处",
        "landmark": "国际商贸城、凤凰山体育公园",
        "navigation_notes": "地铁5号线幸福桥站下车。",
        "opening_hours": "全天",
        "description": "有“城北中央公园”之称，兼具栈道步行、文化展示和休闲游览功能。",
        "service_content": "蜀医养生、国粹文化展示、屋顶栈道徒步",
        "target_people": "周边居民、文化休闲游客、徒步爱好者",
        "image_url": "https://ts4.tc.mm.bing.net/th/id/OIP-C.3QKb7PhZjWZueBsU8iFkrAHaFj?cb=thfc1falcon&rs=1&pid=ImgDetMain&o=7&rm=3",
        "is_featured": False,
        "status": "published",
    },
]


def ensure_default_admin(db) -> None:
    if not db.query(AdminUser).first():
        db.add(
            AdminUser(
                username=settings.admin_username,
                hashed_password=get_password_hash(settings.admin_password),
            )
        )


def ensure_default_categories(db) -> dict[str, Category]:
    categories_by_slug = {category.slug: category for category in db.query(Category).all()}
    for payload in DEFAULT_CATEGORIES:
        if payload["slug"] in categories_by_slug:
            continue
        category = Category(**payload)
        db.add(category)
        db.flush()
        categories_by_slug[category.slug] = category
    return categories_by_slug


def ensure_default_points(db, categories_by_slug: dict[str, Category]) -> None:
    existing_keys = {
        (point.name, point.address)
        for point in db.query(Point.name, Point.address).all()
    }

    for payload in DEFAULT_POINTS:
        key = (payload["name"], payload["address"])
        if key in existing_keys:
            continue

        point_data = dict(payload)
        category_slug = point_data.pop("category_slug")
        point_data["category_id"] = categories_by_slug[category_slug].id
        db.add(Point(**point_data))
        existing_keys.add(key)


def seed_data(db) -> None:
    ensure_default_admin(db)
    categories_by_slug = ensure_default_categories(db)
    ensure_default_points(db, categories_by_slug)
    db.commit()
